variable "private_beta_description" {}
variable "private_beta_volume_size" {}
variable "private_beta_instance_type" {}
variable "private_beta_s3_folder" {}
variable "private_beta_disable_api_stop" {}
variable "private_beta_disable_api_termination" {}
variable "private_beta_availability_zone" {}
variable "private_beta_ebs_delete_on_termination" {}
variable "private_beta_volume_type" {}
variable "private_beta_key_name" {}
variable "private_beta_route53_type" {}
